[config]
secretId = "AKIDjHfmcBt4MN70cdis65oHsDKArJUPJ9x0"
secretKey = "va1C6kUzECuNZbNHuJTNL3UeZWhbFdkS"
domain = "fantasyland.ink"   #主域名
subDomains = ["admin", "rummy", "update", "back"]  #子域名
checkTime = 60  #检查时间, 秒
netCard = "en0"